$(document).ready(function() {
	
	// get the log.txt file generated by git
	$.get('logLexp.txt',function(txt) {
		
        var lines = txt.split("\n");
		var myHtml = '';
		for (var i = 0, len = lines.length; i < len; i++) {
            if (lines[i].length > 0 ) {
				myHtml += "<li>" + lines[i] + "</li>"
			}	
        }
		$('#containerNew ul').append(myHtml);
		
	});
	
	// show/hide the legacy changes
	$('button').on('click', function () {
		if ( $('#container').css('display') == 'none') {
			$('#container').show();
		}
		else {
			$('#container').hide();
		}
	
	});
	
});